[project]
name = "tdde09-students"
version = "2026.01.12"
description = "Course materials for TDDE09 Natural Language Processing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "numpy>=2.4.1",
    "torch>=2.9.1",
]
